### ISSUE TITLE
A little things to consider...

### ISSUE THREAD

**Issue by Mashiane** [DavidBanksNZ/simple-diagram-js#2]
Hi, this is brilliant, thanks

1. This does not work with the latest version of d3, don't you want to revisit this and update it.
2. The interactive property seems broken, when set to true, it does not show anything.
3. The second example does not work at all.
4. Besides the cloudfare link for d3, How can this work with an offline (downloaded) version of d3, which complete sets of files are needed?

Thanks.

**Comment by DavidBanksNZ** [comment]
@Mashiane I will look at updating the code very soon, hopefully in the next week.

**Comment by DavidBanksNZ** [comment]
@Mashiane Second example means example2.html? It seems to work fine for me.

**Comment by DavidBanksNZ** [comment]
@Mashiane Repo is updated and is now D3 v5 compatible. Check docs.md to see the required standalone packages.

Regarding point 2, `interactive` is just a flag for enabling tooltip support. You actually have to add `hoverText` to any nodes you want a tooltip to display.

Regarding working with an offline version of D3, I have now published this on npm (https://www.npmjs.com/package/simple-diagram-js). You can now load the standalone packages from node_modules folder after running `npm install`.

I'll close this issue now as I think all items have been addressed. Do let me know if you have further issues.
